### ISSUE TITLE
I saw a monster walk straight through a tree

### ISSUE THREAD

**Issue by malcolmwalsh** [Flexecute/CommandoGame#2]

**Comment by Flexecute** [comment]
Can you remember which type of monster it was, and if possible, which type of tree? Was it right through the centre of the tree, or just the outside?

**Comment by malcolmwalsh** [comment]
Pretty sure the fire sword and shield dude. Right through the centre of one of the dead trees.

**Comment by Flexecute** [comment]
As I suspected, I hadn't baked the last couple of trees into the scene, should be fixed for next release
